/**:
  ros__parameters:
    # Mocap relay parameters
    asset_name: open_dubs
    tracked_objects: [
      ramp1,
      ramp2,
      block1,
      block2,
      block3,
    ]

    # VRPN parameters
    server: 192.168.0.184
    port: 3883
    update_frequency: 360.0
    frame_id: map
    use_server_time: false
    broadcast_tf: true

    # Odometry parameters
    filter_alpha: 0.2
    parent_frame_id: odom
    child_frame_id: base_link

    # TF offsets in meters and radians (relative to robot frame, x forward, y left, z up)
    offset_x: -0.0309
    offset_y: 0.007
    offset_z: -0.490
    offset_roll: 0.0 
    offset_pitch: 0.0
    offset_yaw: 0.0
